# Generated by Django 2.2.17 on 2020-12-16 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180410_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 16, 15, 26, 53, 155622, tzinfo=utc)),
        ),
    ]
