# Generated by Django 2.2.17 on 2021-01-02 08:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20210102_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 2, 8, 1, 25, 950511, tzinfo=utc)),
        ),
    ]
