# Generated by Django 2.2.17 on 2021-03-26 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20210102_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='classification',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 26, 12, 58, 22, 600711, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 26, 12, 58, 22, 599714, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.TextField(default='EGGS', max_length=300),
        ),
    ]
